language: node_js
os:
  - linux
  - osx
addons:
  ssh_known_hosts:
    - github.com 
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12

cache:
  directories:
    - node_modules
install:
  - npm install 
script:
  - npm test
